<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>This .NET library contains opinionated adapters, extensions, and helper classes for working with infrastructure.</Description>
        <!-- TODO: CS1573 - Fully document all params for documented methods. -->
        <!-- TODO: CS1591 - Fully document all publicly visible members. -->
        <NoWarn>CS1573,CS1591</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Azure.Storage.Blobs"/>
        <PackageReference Include="FluentValidation"/>
        <PackageReference Include="K4os.Compression.LZ4"/>
        <PackageReference Include="Scrutor"/>
        <PackageReference Include="StackExchange.Redis"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\NorthSouthSystems.Opinions.BCL\NorthSouthSystems.Opinions.BCL.csproj"/>
        <ProjectReference Include="..\NorthSouthSystems.Opinions.Infra.Abstractions\NorthSouthSystems.Opinions.Infra.Abstractions.csproj"/>
        <ProjectReference Include="..\NorthSouthSystems.Opinions.Scrutor\NorthSouthSystems.Opinions.Scrutor.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="FluentValidation"/>
        <Using Include="NorthSouthSystems.Scrutor"/>
    </ItemGroup>

</Project>
