using System.Linq.Expressions;
using System.Numerics;
using System.Reflection;

namespace NorthSouthSystems;

// Many interfaces are source generated by Vogen.
//
// Vogen implements IFormattable, ISpanFormattable, IUtf8SpanFormattable; however, it only does so when the
// Type declaration does not already implement those interfaces. This essentially allows Value Objects to bring
// their own IFormattable, and if not, Vogen will provide a default.
//
// Vogen implements IParsable<TSelf>, ISpanParsable<TSelf>, IUtf8SpanParsable<TSelf>; however, it only does so
// when TValue does (but not completely for string? see comment below in IStringValueObject).

#region "Derived" interfaces

public interface IByteValueObject<TSelf> : INumberValueObject<TSelf, byte> where TSelf : struct, IByteValueObject<TSelf>;
public interface IShortValueObject<TSelf> : INumberValueObject<TSelf, short> where TSelf : struct, IShortValueObject<TSelf>;
public interface IIntValueObject<TSelf> : INumberValueObject<TSelf, int> where TSelf : struct, IIntValueObject<TSelf>;
public interface ILongValueObject<TSelf> : INumberValueObject<TSelf, long> where TSelf : struct, ILongValueObject<TSelf>;

public interface IGuidValueObject<TSelf> : IStructValueObject<TSelf, Guid>,
    IParsable<TSelf>, ISpanParsable<TSelf>, IUtf8SpanParsable<TSelf>
    where TSelf : struct, IGuidValueObject<TSelf>;

public interface IStringValueObject<TSelf> : IValueObject<TSelf, string>,
    IParsable<TSelf> // Vogen bug ISpanParsable<TSelf>? string does not implement IUtf8SpanParsable<TSelf>.
    where TSelf : struct, IStringValueObject<TSelf>;

#endregion

#region "Base" interfaces

// We artificially limit TValue to structs so that we can use IStructValueObject and therefore Nullable<IStructValueObject>.
public interface INumberValueObject<TSelf, TValue> : IStructValueObject<TSelf, TValue>,
    IParsable<TSelf>, ISpanParsable<TSelf>, IUtf8SpanParsable<TSelf>
    where TSelf : struct, INumberValueObject<TSelf, TValue>
    where TValue : struct, INumber<TValue>;

public interface IStructValueObject<TSelf, TValue> : IValueObject<TSelf, TValue>
    where TSelf : struct, IStructValueObject<TSelf, TValue>
    where TValue : struct, IComparable<TValue>;

public interface IValueObject<TSelf, TValue>
    // Vogen implements both IEquatable<TSelf> and IEquatable<TValue>; however, that is not possible here due to the
    // below compiler error and because there is no C# capability to constrain that TSelf != TValue:
    // Interface 'Nss.IValueObject<TSelf,TValue>' cannot implement both 'System.IEquatable<TSelf>' and
    // 'System.IEquatable<TValue>' because they may unify for some type parameter substitutions
    : IEquatable<TSelf>, /*IEquatable<TValue>,*/
        IComparable<TSelf>, IComparable
//IFormattable, ISpanFormattable, IUtf8SpanFormattable
    where TSelf : struct, IValueObject<TSelf, TValue>
    where TValue : IComparable<TValue>
{
    TValue Value { get; }
}

#endregion

public static class ValueObjectFactory<TValueObject, TValue>
    where TValueObject : struct, IValueObject<TValueObject, TValue>
    where TValue : IComparable<TValue>
{
#pragma warning disable CA1000 // We're taking advantage of static "one per args" and implicit "locking".
    public static Func<TValue, TValueObject> ConstructNoValidation { get; } = Compile();
#pragma warning restore CA1000

    private static Func<TValue, TValueObject> Compile()
    {
        var ctor = typeof(TValueObject)
            .GetConstructor(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance, [typeof(TValue)]);

        if (ctor is null)
            throw new InvalidOperationException(string.Create(InvariantCulture, $"{typeof(TValueObject).Name}({nameof(TValue)}) constructor must exist."));

        var valueParam = Expression.Parameter(typeof(TValue), "value");
        var @new = Expression.New(ctor, valueParam);
        var lambda = Expression.Lambda<Func<TValue, TValueObject>>(@new, valueParam);

        return lambda.Compile();
    }
}